### ISSUE TITLE
Disabled log JSBR and MG by default.

### ISSUE THREAD

**Issue by llwsh** [leo-buneev/eslint-plugin-md#3]
my english is not good, sorry.
thanks for your works, eslint-plugin-md is amazing for me.
but there is only one trouble prevent i use it in my project.
it is the extra logging about JSBR and MG.
looking forward to your reply 👍

**Comment by leo-buneev** [comment]
Well, that's a bit embarassing.

Thanks for cleaning it up. Merged & published in 1.0.16

**Comment by llwsh** [comment]
Thanks, I have been searching for this plugin for a long time. I found that it perfectly fits my thoughts and needs, and I will use it in my project immediately.
👍👍👍
